name: "Dependabot Security Check"

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *" # Runs daily

permissions:
  security-events: read
  pull-requests: write

jobs:
  check-dependabot-alerts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch Dependabot Security Alerts
        id: get_alerts
        run: |
          curl -s -H "Accept: application/vnd.github+json" \
               -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
               "https://api.github.com/repos/${{ github.repository }}/dependabot/alerts" \
               | jq '[.[] | select(.security_advisory.severity == "critical") | {package: .security_vulnerability.package.name, affected: .security_vulnerability.vulnerable_version_range}]' > critical-alerts.json

      - name: Show Critical Vulnerabilities
        run: |
          echo "🔴 Found the following critical vulnerabilities:"
          jq '.' critical-alerts.json || echo "✅ No critical vulnerabilities found."

      - name: Get Changed Dependency Files
        if: github.event_name == 'pull_request'
        id: changed_files
        run: |
          CHANGED_FILES=$(curl -s -H "Accept: application/vnd.github+json" \
                               -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                               "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files" \
                               | jq -r '.[].filename')

          echo "Changed files: $CHANGED_FILES"
          echo "CHANGED_FILES=$CHANGED_FILES" >> $GITHUB_ENV

      - name: Extract Updated Packages in PR
        if: github.event_name == 'pull_request'
        id: extract_packages
        run: |
          echo "🔍 Checking updated dependencies..."
          UPDATED_PACKAGES=""

          for file in $CHANGED_FILES; do
            if [[ "$file" == *"requirements.txt"* ]]; then
              UPDATED_PACKAGES+=$(grep -Eo '^[a-zA-Z0-9_-]+==[0-9]+\.[0-9]+\.[0-9]+' "$file" | xargs)
            elif [[ "$file" == *"package.json"* ]]; then
              UPDATED_PACKAGES+=$(jq -r '.dependencies | to_entries[] | "\(.key)@\(.value)"' "$file" | xargs)
            fi
          done

          echo "UPDATED_PACKAGES=$UPDATED_PACKAGES" >> $GITHUB_ENV
          echo "🆕 Updated Packages: $UPDATED_PACKAGES"

      - name: Fail PR if Critical Vulnerabilities Remain
        if: github.event_name == 'pull_request'
        run: |
          CRITICAL_COUNT=$(jq 'length' critical-alerts.json)
          FIXED_COUNT=0

          for package in $(jq -r '.[].package' critical-alerts.json); do
            VULNERABLE_RANGE=$(jq -r --arg pkg "$package" 'map(select(.package == $pkg)) | .[].affected' critical-alerts.json)

            if [[ -z "$VULNERABLE_RANGE" ]]; then
              continue
            fi

            echo "🔍 Checking if $package is upgraded outside the vulnerable range: $VULNERABLE_RANGE"

            UPDATED_VERSION=$(echo "$UPDATED_PACKAGES" | grep -oP "$package==\K[0-9]+\.[0-9]+\.[0-9]+")
            
            if [[ -n "$UPDATED_VERSION" && "$UPDATED_VERSION" != "$VULNERABLE_RANGE" ]]; then
              echo "✅ $package is updated to $UPDATED_VERSION (outside vulnerable range)."
              FIXED_COUNT=$((FIXED_COUNT + 1))
            fi
          done

          if [[ "$FIXED_COUNT" -ge "$CRITICAL_COUNT" ]]; then
            echo "✅ PR fixes all critical vulnerabilities. Allowing merge."
            exit 0
          else
            echo "❌ PR does NOT fix all vulnerabilities. Failing pipeline."
            exit 1
          fi

      - name: Fail Pipeline on Critical Vulnerabilities (Push Event)
        if: github.event_name != 'pull_request'
        run: |
          CRITICAL_COUNT=$(jq 'length' critical-alerts.json)

          if [ "$CRITICAL_COUNT" -gt 0 ]; then
            echo "❌ Found $CRITICAL_COUNT critical vulnerabilities!"
            exit 1
          else
            echo "✅ No critical vulnerabilities found."
          fi
